Repository is212g7t5/spm, pull requests merged in 2022-10, with the labels that each got.

#32 [G7T5-95] Create LJ and LJ Course APIs
  backend/alembic/versions/0006_create_learning_journey_and_course.py
  backend/app/api/api_v1/api.py
  backend/app/api/api_v1/endpoints/learning_journey.py
  backend/app/api/api_v1/endpoints/learning_journey_course.py
  backend/app/crud/__init__.py
  backend/app/crud/crud_learning_journey.py
  backend/app/crud/crud_learning_journey_course.py
  backend/app/models/__init__.py
  backend/app/models/learning_journey.py
  backend/app/models/learning_journey_course.py
  backend/app/models/skill_course.py
  backend/app/schemas/__init__.py
  backend/app/schemas/learning_journey.py
  backend/app/schemas/learning_journey_course.py
  backend/app/tests/api/api_v1/test_learning_journey.py
  backend/app/tests/api/api_v1/test_learning_journey_course.py
  backend/app/tests/crud/test_learning_journey.py
  backend/app/tests/crud/test_learning_journey_course.py
  backend/app/tests/utils/learning_journey.py
  backend/app/tests/utils/learning_journey_course.py
  backend/app/tests/utils/staff.py
  backend/app/tests/utils/utils.py
Labels: ready to review, backend

#35 [G7T5-76] Refactor code and touch up context API
  app/.eslintrc.json
  app/src/App.jsx
  app/src/components/Navbar.jsx
  app/src/components/course/index.jsx
  app/src/components/user/Login.jsx
  app/src/components/user/UserContext.jsx
  app/src/components/user/UserNavigation.jsx
  app/src/contexts/UserContext.jsx
  app/src/layout/Login.jsx
  app/src/layout/Navbar.jsx
  app/src/layout/UserNavigation.jsx
  app/src/layout/index.jsx
  app/src/routes/courses/index.jsx
  app/src/routes/createLearningJourney/index.jsx
  app/src/routes/index.jsx
  app/src/routes/jobs/index.jsx
  app/src/routes/learningJourneys/index.jsx
  app/src/utils/helpers.js
Labels: ready to review, frontend

#38 [G7T5-79, G7T5-96] Add HR Job Page with Access Control
  app/src/components/job/JobTile.jsx
  app/src/components/job/hr/HRJob.jsx
  app/src/components/job/index.jsx
  app/src/components/job/staff/StaffJob.jsx
  app/src/contexts/UserContext.jsx
Labels: ready to review, frontend

#40 Add create new job button for HR
  app/src/components/job/hr/HRJob.jsx
  app/src/routes/jobs/index.jsx
Labels: ready to review, frontend

#41 [G7T5-99] Created Colour Scheme
  app/src/layout/Login.jsx
  app/src/layout/Navbar.jsx
  app/tailwind.config.js
Labels: ready to review, frontend

#43 [G7T5-91] Retrieved Job details from Learning Journeys
  app/src/api/jobs.js
  app/src/api/learningJourney.js
  app/src/components/learningJourney/LearningJourneyTile.jsx
  app/src/components/learningJourney/index.jsx
  app/src/components/learningJourney/staff/StaffLearningJourney.jsx
  app/src/contexts/UserContext.jsx
Labels: ready to review, frontend

#46 Add netlify url to list of accepted origins
  backend/app/core/config.py
Labels: ready to review, backend

#48 [G7T5-60] Staff Initiate Learning Journey Creation
  app/package-lock.json
  app/package.json
  app/src/App.jsx
  app/src/api/jobs.js
  app/src/api/skills.js
  app/src/components/createLearningJourney/index.jsx
  app/src/components/job/JobTile.jsx
  app/src/components/job/hr/HRJob.jsx
  app/src/components/job/staff/StaffJob.jsx
  app/src/components/learningJourney/LearningJourneyTile.jsx
  app/src/components/learningJourney/staff/StaffLearningJourney.jsx
  app/src/contexts/LJCreationContext.jsx
  app/src/contexts/UserContext.jsx
  app/src/layout/Navbar.jsx
  app/src/routes/createLearningJourney/index.jsx
  app/src/routes/createLearningJourneyPage/index.jsx
  app/src/routes/index.jsx
Labels: ready to review, frontend, backend

#47 [G7T5-82] Add edit job button for HR
  app/src/components/job/JobTile.jsx
Labels: ready to review, frontend

#50 [G7T5-83, G7T5-84] Create update job page for HR
  app/src/App.jsx
  app/src/api/jobs.js
  app/src/components/job/JobTile.jsx
  app/src/components/job/hr/CreateJob.jsx
  app/src/components/job/hr/UpdateJob.jsx
  app/src/components/job/hr/UpdateJobSuccess.jsx
  app/src/contexts/UpdateJobContext.jsx
  app/src/routes/index.jsx
  app/src/routes/updateJob/index.jsx
Labels: ready to review, frontend

#55 [G7T5-117] Setup Create LJ Course mapping API
  app/src/api/config.js
  app/src/api/learningJourneyCourse.js
Labels: ready to review, frontend

#54 [G7T5-81] Add access control to update job
  app/src/components/job/hr/CreateJob.jsx
  app/src/components/job/hr/UpdateJob.jsx
  app/src/components/job/hr/form/JobDescTextArea.jsx
  app/src/components/job/hr/form/JobIsActiveToggle.jsx
  app/src/components/job/hr/form/JobNameInput.jsx
Labels: ready to review, frontend

#59 [G7T5-120] Fix bug where LJ was not displaying
  app/src/api/jobs.js
  app/src/components/learningJourney/staff/StaffLearningJourney.jsx
  app/src/contexts/UserContext.jsx
Labels: ready to review, frontend

#53 [G7T5-70 & G7T5-71] Create LJ Deletion FE and BE
  app/src/api/learningJourney.js
  app/src/api/learningJourneyCourse.js
  app/src/components/learningJourney/DropdownButton.jsx
  app/src/components/learningJourney/LearningJourneyTile.jsx
  app/src/components/learningJourney/details/LJDeletionPopUp.jsx
  app/tailwind.config.js
  backend/app/api/api_v1/endpoints/learning_journey_course.py
  backend/app/crud/crud_learning_journey_course.py
  backend/app/tests/api/api_v1/test_learning_journey_course.py
Labels: frontend, backend

#61 [G7T5-125] Add is_active query param for /job/skills
  backend/app/api/api_v1/endpoints/job.py
  backend/app/crud/crud_job.py
  backend/app/schemas/job.py
  backend/app/tests/api/api_v1/test_job.py
  backend/app/tests/utils/job.py
  backend/app/tests/utils/job_skill.py
Labels: ready to review, backend

#60 [G7T5-122] Close access to inactive Skills for non-HR
  app/src/api/skills.js
  app/src/components/job/staff/StaffJob.jsx
  app/src/components/skill/SkillTile.jsx
  app/src/components/skill/index.jsx
  app/src/components/skill/staff/StaffSkill.jsx
  backend/app/api/api_v1/endpoints/skill.py
  backend/app/crud/base.py
  backend/app/tests/api/api_v1/test_skill.py
  backend/app/tests/utils/skill.py
  backend/app/tests/utils/skill_course.py
Labels: ready to review

#63 [G7T5-127] [G7T5-128] Reused Staff Job component for Manager
  app/src/components/job/index.jsx
Labels: ready to review, frontend

#62 [G7T5-126] Display only active jobs for Staff
  app/src/api/jobs.js
  app/src/components/job/staff/StaffJob.jsx
Labels: ready to review, frontend

#67 [G7T5-134] Call BE API to get all skills for HRSkill
  app/src/components/skill/hr/HRSkill.jsx
  app/src/components/skill/staff/StaffSkill.jsx
Labels: ready to review, frontend

#64 [G7T5-92] Create Submit Button for 'Create Learning Journey' and included staffId in UserContext
  app/src/api/learningJourney.js
  app/src/api/learningJourneyCourse.js
  app/src/components/createLearningJourney/SubmitButton.jsx
  app/src/components/createLearningJourney/index.jsx
  app/src/contexts/UserContext.jsx
  app/src/layout/Login.jsx
  app/src/layout/UserNavigation.jsx
Labels: ready to review, frontend

#69 [G7T5-119] Streamline css - breaking change
  app/src/components/SearchBar.jsx
  app/src/components/course/CourseStatusBadge.jsx
  app/src/components/course/CourseTile.jsx
  app/src/components/createLearningJourney/CourseModal.jsx
  app/src/components/createLearningJourney/CoursesList.jsx
  app/src/components/createLearningJourney/JobSkills.jsx
  app/src/components/createLearningJourney/index.jsx
  app/src/components/job/JobTile.jsx
  app/src/components/job/SkillBadge.jsx
  app/src/components/job/hr/CreateJob.jsx
  app/src/components/job/hr/CreateJobSuccess.jsx
  app/src/components/job/hr/HRJob.jsx
  app/src/components/job/hr/UpdateJob.jsx
  app/src/components/job/hr/UpdateJobSuccess.jsx
  app/src/components/job/hr/form/JobDescTextArea.jsx
  app/src/components/job/hr/form/JobIsActiveToggle.jsx
  app/src/components/job/hr/form/JobNameInput.jsx
  app/src/components/learningJourney/DropdownButton.jsx
  app/src/components/learningJourney/LearningJourneyTile.jsx
  app/src/components/learningJourney/details/AddCourseButton.jsx
  app/src/components/learningJourney/details/CourseCard.jsx
  app/src/components/learningJourney/details/CourseContainer.jsx
  app/src/components/learningJourney/details/CourseSkillBadge.jsx
  app/src/components/learningJourney/details/JobBadge.jsx
  app/src/components/learningJourney/details/JobSkillBadge.jsx
  app/src/components/learningJourney/details/LJDeletionPopUp.jsx
  app/src/components/skill/CourseBadge.jsx
  app/src/components/skill/SkillTile.jsx
  app/src/layout/Login.jsx
  app/src/layout/Navbar.jsx
  app/src/layout/UserNavigation.jsx
  app/tailwind.config.js
Labels: ready to review, frontend

#68 [G7T5-129] Add create skill button for HR
  app/src/components/skill/hr/HRSkill.jsx
  app/src/components/skill/staff/StaffSkill.jsx
  app/src/routes/skills/index.jsx
Labels: ready to review, frontend

#70 [G7T5-104] Edit Skill button for HR
  app/src/components/skill/SkillTile.jsx
Labels: ready to review, frontend

#72 [Bugfix] Fixed Error when writing new LJ and Course mappings
  app/src/api/learningJourneyCourse.js
  app/src/components/createLearningJourney/index.jsx
  app/src/contexts/UserContext.jsx
Labels: ready to review, frontend

#66 [G7T5-121] Fix LJ Deletion Popup
  app/src/api/learningJourney.js
  app/src/components/learningJourney/DropdownButton.jsx
  app/src/components/learningJourney/LearningJourneyTile.jsx
  app/src/components/learningJourney/details/LJDeletionPopUp.jsx
  app/src/components/learningJourney/staff/StaffLearningJourney.jsx
Labels: ready to review, frontend

#75 [G7T5-131] Add backend validation for skill fields
  backend/alembic/versions/0009_alter_skill_table.py
  backend/app/api/api_v1/endpoints/skill.py
  backend/app/crud/crud_skill.py
  backend/app/schemas/skill.py
  backend/app/tests/api/api_v1/test_skill.py
Labels: ready to review, backend

#74 [G7T5-131] Trigger backend request to create skill
  app/src/api/skills.js
  app/src/components/job/hr/CreateJob.jsx
  app/src/components/skill/hr/CreateSkill.jsx
  app/src/components/skill/hr/CreateSkillSuccess.jsx
  app/src/components/skill/hr/HRSkill.jsx
Labels: ready to review, frontend

#79 [G7T5-72] Create FE Components when Staff deletes courses in new LJ
  app/src/components/createLearningJourney/CoursesList.jsx
  app/src/components/createLearningJourney/DeleteSkillModal.jsx
  app/src/components/createLearningJourney/index.jsx
Labels: ready to review, frontend

#78 [G7T5-132] Add access control to create-skill page
  app/src/components/skill/hr/CreateSkill.jsx
  app/src/layout/Login.jsx
Labels: ready to review, frontend

#77 [G7T5-102, G7T5-103, G7T5-140] Add and remove courses from existing LJ
  app/src/App.jsx
  app/src/api/learningJourney.js
  app/src/api/learningJourneyCourse.js
  app/src/components/createLearningJourney/CourseModal.jsx
  app/src/components/createLearningJourney/CoursesList.jsx
  app/src/components/createLearningJourney/SubmitButton.jsx
  app/src/components/createLearningJourney/index.jsx
  app/src/components/job/JobTile.jsx
  app/src/components/learningJourney/details/AddCourseButton.jsx
  app/src/components/learningJourney/details/CourseCard.jsx
  app/src/components/learningJourney/details/CourseContainer.jsx
  app/src/components/learningJourney/details/JobAndSkillsContainer.jsx
  app/src/components/learningJourney/details/index.jsx
  app/src/contexts/LJContext.jsx
Labels: ready to review, testing, frontend

#80 [G7T5-136 & G7T5-137] Create HR Soft-Delete Skills
  app/src/api/skills.js
  app/src/components/skill/SkillTile.jsx
  app/src/components/skill/hr/DeactivateSkillModal.jsx
  app/src/components/skill/hr/HRSkill.jsx
  app/src/components/skill/hr/StopDeactivateSkillModal.jsx
Labels: ready to review, frontend

#82 [G7T5-142, G7T5-144] Create and link FE for UpdateSkill page
  app/src/App.jsx
  app/src/components/skill/SkillTile.jsx
  app/src/components/skill/hr/UpdateSkill.jsx
  app/src/components/skill/hr/UpdateSkillSuccess.jsx
  app/src/components/skill/hr/form/SkillIsActiveToggle.jsx
  app/src/contexts/UpdateSkillContext.jsx
  app/src/routes/index.jsx
  app/src/routes/updateSkill/index.jsx
Labels: ready to review, frontend

#83 [G7T5-143] Call BE API to update skill for HR
  app/src/api/skills.js
  app/src/components/skill/SkillTile.jsx
  app/src/components/skill/hr/DeactivateSkillModal.jsx
  app/src/components/skill/hr/UpdateSkill.jsx
Labels: ready to review, frontend

#84 [G7T5-148] Route Manager Skills page to Staff's Skills page
  app/src/components/skill/index.jsx
Labels: ready to review, frontend

#85 [G7T5-145] Display LJs for inactive job roles, disable editing of LJ
  app/src/components/learningJourney/DropdownButton.jsx
  app/src/components/learningJourney/LearningJourneyTile.jsx
  app/src/components/learningJourney/details/AddCourseButton.jsx
  app/src/components/learningJourney/details/JobBadge.jsx
  app/src/components/learningJourney/details/index.jsx
  app/src/components/learningJourney/staff/StaffLearningJourney.jsx
Labels: ready to review, frontend

#73 [G7T5-74, G7T5-75] Create FE View for HR to Delete Job Roles
  app/src/api/jobs.js
  app/src/components/job/JobTile.jsx
  app/src/components/job/hr/HRJob.jsx
  app/src/components/job/hr/JobDeletionPopUp.jsx
  backend/package-lock.json
  backend/package.json
Labels: ready to review, frontend

#88 [G7T5-150] Fix LJ Refreshing due to LJ Deletion
  app/src/components/learningJourney/DropdownButton.jsx
  app/src/components/learningJourney/LearningJourneyTile.jsx
  app/src/components/learningJourney/details/LJDeletionPopUp.jsx
  app/src/components/learningJourney/staff/StaffLearningJourney.jsx
Labels: ready to review, frontend

#90 [G7T5-176] Update backend README
  backend/.env-example
  backend/README.md
Labels: ready to review, backend

#91 [G7T5-99] Fix Navbar bug where clicking on tabs does not register
  app/src/layout/Navbar.jsx
Labels: ready to review, frontend

#89 [G7T5-175] Update frontend README
  app/.env-example
  app/README.md
Labels: ready to review, frontend

#92 [G7T5-177] Update overall README
  README.md
Labels: ready to review
