Repository is212g7t5/spm, pull requests merged in 2022-11, with the labels that each got.

#97 [G7T5-151] Display only active courses when selecting a Skill in LJ
  app/src/components/createLearningJourney/CourseModal.jsx
Labels: ready to review, frontend

#98 [G7T5-195] Display only active courses in /courses page
  app/src/components/course/CourseTile.jsx
Labels: ready to review, frontend

#96 [G7T5-192] Create Endpoint for All Courses with Active Skills
  backend/app/api/api_v1/endpoints/course.py
  backend/app/tests/api/api_v1/test_course.py
  backend/app/tests/utils/course.py
  backend/app/tests/utils/skill_course.py
Labels: ready to review, backend

#95 [G7T5-161, G7T5-162] Staff view only own Learning Journey
  app/src/App.jsx
  app/src/components/learningJourney/details/AddCourseButton.jsx
  app/src/components/learningJourney/details/index.jsx
  app/src/components/learningJourney/staff/StaffLearningJourney.jsx
  app/src/contexts/StaffContext.jsx
Labels: ready to review, frontend

#94 [G7T5-170] Lower Z-index of login button
  app/src/components/createLearningJourney/CourseModal.jsx
  app/src/layout/Login.jsx
Labels: ready to review, frontend

#100 [G7T5-158] Truncate Job Description
  app/src/components/job/JobTile.jsx
  app/src/components/skill/SkillTile.jsx
Labels: ready to review, frontend

#103 [G7T5-179] [G7T5-180] Standardised Tailwind classes used in Job Role and LJ flows
  app/src/components/SearchBar.jsx
  app/src/components/createLearningJourney/CourseModal.jsx
  app/src/components/createLearningJourney/CoursesList.jsx
  app/src/components/createLearningJourney/SubmitButton.jsx
  app/src/components/job/JobTile.jsx
  app/src/components/job/SkillBadge.jsx
  app/src/components/job/hr/CreateJob.jsx
  app/src/components/job/hr/CreateJobSuccess.jsx
  app/src/components/job/hr/HRJob.jsx
  app/src/components/job/hr/JobDeletionPopUp.jsx
  app/src/components/job/hr/UpdateJob.jsx
  app/src/components/job/hr/UpdateJobSuccess.jsx
  app/src/components/job/hr/form/JobDescTextArea.jsx
  app/src/components/job/hr/form/JobIsActiveToggle.jsx
  app/src/components/job/hr/form/JobNameInput.jsx
  app/src/components/job/staff/StaffJob.jsx
  app/src/layout/Login.jsx
  app/src/layout/Navbar.jsx
  app/tailwind.config.js
Labels: ready to review, frontend

#102 [G7T5-149] Fix Duplicate Skill Name for HR Update Skill
  backend/app/api/api_v1/endpoints/skill.py
  backend/app/schemas/skill.py
Labels: ready to review, backend

#109 [G7T5-169] Handle overflow for course description for course card in create LJ flow
  app/src/components/createLearningJourney/CoursesList.jsx
Labels: ready to review, frontend

#106 [G7T5-156, G7T5-157, G7T5-165] Staff cannot view and select inactive courses or skills
  app/src/components/createLearningJourney/CourseModal.jsx
  app/src/components/createLearningJourney/CoursesList.jsx
  app/src/components/createLearningJourney/JobSkills.jsx
  app/src/components/createLearningJourney/index.jsx
Labels: ready to review, testing, frontend

#105 [G7T5-146] Only display active skills for all cases for Staff
  app/src/api/course.js
  app/src/api/jobs.js
  app/src/components/course/CourseDescription.jsx
  app/src/components/course/CourseTile.jsx
  app/src/components/course/SkillBadge.jsx
  app/src/components/course/hr/HRCourse.jsx
  app/src/components/course/staff/StaffCourse.jsx
  app/src/components/job/staff/StaffJob.jsx
  app/src/components/learningJourney/details/JobAndSkillsContainer.jsx
  app/src/components/learningJourney/details/index.jsx
  backend/app/api/api_v1/endpoints/job.py
  backend/app/api/api_v1/endpoints/skill.py
Labels: ready to review, frontend

#107 [G7T5-182] Standardised Tailwind classes in Courses Flow
  app/src/components/course/staff/StaffCourse.jsx
Labels: ready to review, frontend

#108 [G7T5-181] Standardised Tailwind classes in Skills flow
  app/src/components/course/hr/HRCourse.jsx
  app/src/components/createLearningJourney/CourseModal.jsx
  app/src/components/createLearningJourney/CoursesList.jsx
  app/src/components/createLearningJourney/DeleteSkillModal.jsx
  app/src/components/createLearningJourney/SubmitButton.jsx
  app/src/components/createLearningJourney/index.jsx
  app/src/components/job/hr/HRJob.jsx
  app/src/components/job/hr/JobDeletionPopUp.jsx
  app/src/components/job/hr/UpdateJob.jsx
  app/src/components/job/hr/form/JobIsActiveToggle.jsx
  app/src/components/job/staff/StaffJob.jsx
  app/src/components/learningJourney/LearningJourneyTile.jsx
  app/src/components/learningJourney/details/AddCourseButton.jsx
  app/src/components/learningJourney/details/LJDeletionPopUp.jsx
  app/src/components/learningJourney/staff/StaffLearningJourney.jsx
  app/src/components/skill/CourseBadge.jsx
  app/src/components/skill/SkillTile.jsx
  app/src/components/skill/hr/CreateSkill.jsx
  app/src/components/skill/hr/CreateSkillSuccess.jsx
  app/src/components/skill/hr/DeactivateSkillModal.jsx
  app/src/components/skill/hr/HRSkill.jsx
  app/src/components/skill/hr/StopDeactivateSkillModal.jsx
  app/src/components/skill/hr/UpdateSkill.jsx
  app/src/components/skill/hr/UpdateSkillSuccess.jsx
  app/src/components/skill/hr/form/SkillDescTextArea.jsx
  app/src/components/skill/hr/form/SkillIsActiveToggle.jsx
  app/src/components/skill/hr/form/SkillNameInput.jsx
  app/src/components/skill/staff/StaffSkill.jsx
Labels: ready to review, frontend

#112 [G7T5-185] [G7T5-186] Standardised Soft Delete Job Role and Skill Flow
  app/src/components/job/JobTile.jsx
  app/src/components/skill/SkillTile.jsx
Labels: ready to review, frontend

#110 [G7T5-196] Create Endpoint to Delete All Skills of A Job
  backend/app/api/api_v1/endpoints/job_skill.py
  backend/app/crud/crud_job_skill.py
  backend/app/tests/api/api_v1/test_job_skill.py
  backend/app/tests/crud/test_job_skill.py
Labels: ready to review, backend

#117 [G7T5-163] Remove inherited staff permissions on views
  app/src/components/job/JobTile.jsx
  app/src/components/job/index.jsx
  app/src/components/skill/index.jsx
  app/src/layout/Navbar.jsx
Labels: ready to review, frontend

#115 [G7T5-154 & G7T5-164] Fix Error Message Handling for Existing Skill Name when Creating and Updating Skill
  app/src/api/skills.js
  app/src/components/skill/hr/CreateSkill.jsx
  app/src/components/skill/hr/UpdateSkill.jsx
Labels: ready to review, frontend

#101 [G7T5-188,189,190 & 194] HR Assign Skills to Course and Remove Skills from Course
  app/src/App.jsx
  app/src/api/skillCourse.js
  app/src/api/skills.js
  app/src/components/course/CourseTile.jsx
  app/src/components/course/UpdateConfirmationPopUp.jsx
  app/src/components/course/UpdateCourse.jsx
  app/src/components/skill/hr/UpdateSkill.jsx
  app/src/contexts/UpdateCourseContext.jsx
  app/src/routes/index.jsx
  app/src/routes/updateCourse/index.jsx
Labels: ready to review, frontend

#111 [G7T5-9 & G7T5-197] HR Add and Remove Skills from Job Role
  app/src/api/jobSkill.js
  app/src/components/course/CourseDescription.jsx
  app/src/components/course/SkillBadge.jsx
  app/src/components/job/JobTile.jsx
  app/src/components/job/hr/CreateJob.jsx
  app/src/components/job/hr/CreateJobSuccess.jsx
  app/src/components/job/hr/UpdateJob.jsx
  app/src/components/job/hr/UpdateJobSuccess.jsx
  app/src/components/job/hr/form/JobDescTextArea.jsx
  app/src/components/job/hr/form/JobIsActiveToggle.jsx
  app/src/components/job/hr/form/JobNameInput.jsx
  app/src/components/job/hr/form/JobSkillSelection.jsx
  app/src/components/skill/CourseBadge.jsx
  app/src/components/skill/SkillTile.jsx
Labels: ready to review, frontend

#118 [G7T5-178] Update main README with feature descriptions
  README.md
  assets/access_control_toggle.png
  assets/hr/courses.png
  assets/hr/create_job.png
  assets/hr/create_skill.png
  assets/hr/deactivate_job.png
  assets/hr/deactivate_skill.png
  assets/hr/edit_course.png
  assets/hr/edit_job.png
  assets/hr/edit_skill.png
  assets/hr/jobs.png
  assets/hr/skills.png
  assets/session_storage.png
  assets/staff/courses.png
  assets/staff/create_learning_journey.png
  assets/staff/create_learning_journey_skill_course.png
  assets/staff/edit_learning_journey.png
  assets/staff/jobs.png
  assets/staff/learning_journey.png
  assets/staff/learning_journey_detail.png
  assets/staff/learning_journey_menu.png
  assets/staff/learning_journey_skill_course.png
  assets/staff/skills.png
Labels: ready to review

#119 [G7T5-170] Cleanup modals and login
  app/src/components/course/index.jsx
  app/src/components/createLearningJourney/CourseModal.jsx
  app/src/components/createLearningJourney/DeleteSkillModal.jsx
  app/src/components/job/JobTile.jsx
  app/src/components/job/index.jsx
  app/src/components/job/staff/StaffJob.jsx
  app/src/components/learningJourney/details/LJDeletionPopUp.jsx
  app/src/components/learningJourney/index.jsx
  app/src/components/learningJourney/staff/StaffLearningJourney.jsx
  app/src/components/skill/hr/DeactivateSkillModal.jsx
  app/src/components/skill/hr/HRSkill.jsx
  app/src/components/skill/hr/StopDeactivateSkillModal.jsx
  app/src/components/skill/index.jsx
Labels: ready to review, frontend
