Repository is212g7t5/spm, pull requests merged in 2022-09, with the labels that each got.

#3 [G7T5-39] Add load_env module and healthcheck endpoint
  app/package-lock.json
  app/yarn.lock
  backend/.env-example
  backend/.gitignore
  backend/README.md
  backend/app/api/api_v1/api.py
  backend/app/core/config.py
  backend/requirements.txt
  backend/scripts/format-imports.sh
  backend/scripts/format.sh
  backend/scripts/test-cov-html.sh
  backend/scripts/test.sh
Labels: testing, backend

#5 Add netlify config to only build on FE change
  app/netlify.toml
Labels: ready to review, frontend

#8 [G7T5-33] Create nodejs.yml
  .github/workflows/node.js.yml
  app/.eslintrc.json
  app/.husky/pre-commit
  app/.prettierrc
  app/package-lock.json
  app/package.json
  app/postcss.config.js
  app/src/App.jsx
  app/src/App.test.jsx
  app/src/index.jsx
  app/src/reportWebVitals.js
  app/tailwind.config.js
  app/yarn.lock
Labels: ready to review, backend

#4 [G7T5-40] Skill components in DB
  backend/alembic/versions/0002_create_skills.py
  backend/app/models/__init__.py
  backend/app/models/skill.py
  backend/app/schemas/__init__.py
  backend/app/schemas/role.py
  backend/app/schemas/skill.py
Labels: needs fix, backend

#2 [G7T5-38] Create preliminary UI components
  app/package-lock.json
  app/package.json
  app/src/components/Navbar.js
  app/src/components/SearchBar.js
Labels: frontend

#12 Fix failing Skill table
  backend/alembic/versions/0002_create_skills.py
  backend/app/models/skill.py
Labels: ready to review, backend

#7 [G7T5-34] Create python-app.yml for CI
  .github/workflows/python-app.yml
  app/.eslintrc.json
  app/package.json
  app/src/components/Navbar.jsx
  app/src/components/SearchBar.js
  app/src/components/SearchBar.jsx
  app/yarn.lock
  backend/.pre-commit-config.yaml
  backend/alembic/versions/0002_create_skills.py
  backend/app/schemas/role.py
  backend/app/tests/crud/test_role.py
  backend/app/tests/utils/role.py
  backend/requirements.txt
Labels: ready to review, frontend

#15 [G7T5-53] Create View for Courses
  app/package-lock.json
  app/package.json
  app/src/App.jsx
  app/src/App.test.jsx
  app/src/components/course/CourseDescription.jsx
  app/src/components/course/CourseTile.jsx
  app/src/components/course/index.jsx
  app/src/routes/courses/index.jsx
Labels: ready to review, frontend

#16 [G7T5-47] Added Course Status Badge
  app/src/components/course/CourseStatusBadge.jsx
  app/src/components/course/CourseTile.jsx
  app/src/components/course/index.jsx
Labels: ready to review, frontend

#23 Updated PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ready to review

#26 [G7T5-89] Updated Course Status with Registration and Completion status
  app/src/App.jsx
  app/src/components/course/CourseStatusBadge.jsx
  app/src/components/course/CourseTile.jsx
  app/src/components/course/index.jsx
Labels: ready to review, frontend

#29 [G7T5-62] Add sessionstorage and context user
  app/src/App.jsx
  app/src/components/Navbar.jsx
  app/src/components/course/index.jsx
  app/src/components/course/staff/StaffCourse.jsx
  app/src/components/user/Login.jsx
  app/src/components/user/UserContext.jsx
  app/src/components/user/UserNavigation.jsx
Labels: ready to review, frontend
